#
# Makefile for memory devices
#

ifeq ($(CONFIG_DDR),y)
obj-$(CONFIG_OF)		+= of_memory.o
endif
obj-$(CONFIG_TI_EMIF)		+= emif.o
obj-$(CONFIG_TEGRA20_MC)	+= tegra20-mc.o
obj-$(CONFIG_TEGRA30_MC)	+= tegra30-mc.o
obj-$(CONFIG_EXYNOS_MCOMP)	+= exynos-mcomp.o
obj-$(CONFIG_EXYNOS7420_MC)	+= exynos7420-mc.o
