# Exynos FMP makefile
obj-$(CONFIG_FIPS_FMP) += first_file.o
obj-$(CONFIG_FIPS_FMP) += fips-fmp.o fips-fmp-integrity.o
obj-$(CONFIG_FIPS_FMP) += last_file.o
obj-$(CONFIG_UFS_FMP_ECRYPT_FS) += fmp_derive_iv.o
