#
# Makefile for linux/drivers/platform/exynos
# exynos Platform-Specific Drivers
#

# fiq debugger
obj-$(CONFIG_FIQ_DEBUGGER) += exynos_fiq_debugger.o

# ramoops
obj-$(CONFIG_PSTORE_RAM) += exynos_ramoops.o