mz-rohm-ois-module-objs := OIS_main.o \
        OIS_func.o \
        OIS_user.o \
        OIS_meizu.o

obj-$(CONFIG_MZ_ROHM_OIS) += mz-rohm-ois-module.o

EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2/include
