obj-$(CONFIG_PM_DEVFREQ)	+= devfreq.o
obj-$(CONFIG_DEVFREQ_GOV_SIMPLE_ONDEMAND)	+= governor_simpleondemand.o
obj-$(CONFIG_DEVFREQ_GOV_SIMPLE_EXYNOS)	+= governor_simpleexynos.o
obj-$(CONFIG_DEVFREQ_GOV_SIMPLE_USAGE)	+= governor_simpleusage.o
obj-$(CONFIG_DEVFREQ_GOV_PERFORMANCE)	+= governor_performance.o
obj-$(CONFIG_DEVFREQ_GOV_POWERSAVE)	+= governor_powersave.o
obj-$(CONFIG_DEVFREQ_GOV_USERSPACE)	+= governor_userspace.o

# DEVFREQ Drivers
obj-$(CONFIG_EXYNOS_TRAFFIC_MONITOR)	+= exynos_traffic_monitor.o

# DEVFREQ Drivers
obj-$(CONFIG_ARM_EXYNOS4_BUS_DEVFREQ)	+= exynos4_bus.o
obj-$(CONFIG_ARM_EXYNOS5422_BUS_DEVFREQ)	+= exynos5422_bus_mif.o exynos5422_bus_int.o exynos5422_bus_isp.o exynos5422_ppmu.o exynos_ppmu.o noc_probe.o
obj-$(CONFIG_ARM_EXYNOS5430_BUS_DEVFREQ)	+= exynos5430_bus_mif.o exynos5430_bus_int.o exynos5430_bus_disp.o exynos5430_bus_isp.o exynos5430_ppmu.o exynos_ppmu2.o
obj-$(CONFIG_ARM_EXYNOS5433_BUS_DEVFREQ)	+= exynos5433_bus.o exynos5_bus_mif.o exynos5_bus_int.o exynos5_bus_disp.o exynos5_bus_isp.o exynos5433_ppmu.o exynos_ppmu_fw.o FW_exynos_ppmu.o
obj-$(CONFIG_ARM_EXYNOS7420_BUS_DEVFREQ)	+= exynos7420_bus.o exynos7_bus_mif.o exynos7_bus_disp.o exynos7_bus_int.o exynos7_bus_isp.o exynos7420_ppmu.o exynos_ppmu_fw.o FW_exynos_ppmu.o
obj-$(CONFIG_ARM_EXYNOS7580_BUS_DEVFREQ)	+= exynos7580_bus.o exynos7580_bus_mif.o exynos7580_bus_int.o exynos7580_bus_isp.o exynos7580_ppmu.o exynos_ppmu_fw.o FW_exynos_ppmu.o
obj-$(CONFIG_SAMSUNG_NOCP_MONITOR) += nocp_monitor.o monitor.o
