snd-soc-meizu-audio-objs := meizu_audio_primary.o meizu_audio_hifi.o board-meizu-audio.o

snd-soc-dummy-audio-objs := dummy_audio.o

obj-$(CONFIG_SND_SOC_MEIZU_AUDIO) += snd-soc-meizu-audio.o

obj-$(CONFIG_SND_SOC_DUMMY_AUDIO) += snd-soc-dummy-audio.o

# obj-$(CONFIG_SND_SOC_ES705_ESCORE) += audience/
