#################################################
# Makefile for JPEG4
# 2013 (C) Samsung Electronics
#################################################

jpeg-objs := jpeg-core.o jpeg-regs.o jpeg-controls.o
obj-$(CONFIG_MEDIA_EXYNOS_JPEG)	+= jpeg.o
