/*
 * Copyright (c) 2014 Samsung Electronics Co., Ltd.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * Device Tree binding constants for Exynos7420 clock controller.
 */

#ifndef _DT_BINDINGS_CLOCK_EXYNOS_7420_H
#define _DT_BINDINGS_CLOCK_EXYNOS_7420_H

#define CLK_SYSMMU_BASE	1500

#define CLK_ACLK_SYSMMU_MSCL0			(CLK_SYSMMU_BASE + 0)
#define CLK_ACLK_SYSMMU_MSCL1			(CLK_SYSMMU_BASE + 1)
#define CLK_PCLK_SYSMMU_MSCL0			(CLK_SYSMMU_BASE + 2)
#define CLK_PCLK_SYSMMU_MSCL1			(CLK_SYSMMU_BASE + 3)

#define CLK_ACLK_G2D_SYSMMU			(CLK_SYSMMU_BASE + 5)
#define CLK_PCLK_G2D_SYSMMU			(CLK_SYSMMU_BASE + 6)

#define CLK_ACLK_DISP_RO_SYSMMU			(CLK_SYSMMU_BASE + 7)
#define CLK_ACLK_DISP_RW_SYSMMU			(CLK_SYSMMU_BASE + 8)
#define CLK_PCLK_DISP_RO_SYSMMU			(CLK_SYSMMU_BASE + 9)
#define CLK_PCLK_DISP_RW_SYSMMU			(CLK_SYSMMU_BASE + 10)

#define CLK_ACLK_CAM0_SYSMMU			(CLK_SYSMMU_BASE + 11)
#define CLK_PCLK_CAM0_SYSMMU			(CLK_SYSMMU_BASE + 12)
#define CLK_ACLK_FIMC_SC_SYSMMU			(CLK_SYSMMU_BASE + 15)
#define CLK_PCLK_FIMC_SC_SYSMMU			(CLK_SYSMMU_BASE + 16)
#define CLK_ACLK_VRA_SYSMMU			(CLK_SYSMMU_BASE + 17)
#define CLK_PCLK_VRA_SYSMMU			(CLK_SYSMMU_BASE + 18)
#define CLK_ACLK_ISPCPU_SYSMMU			(CLK_SYSMMU_BASE + 19)
#define CLK_PCLK_ISPCPU_SYSMMU			(CLK_SYSMMU_BASE + 20)
#define CLK_ACLK_ISP1_SYSMMU			(CLK_SYSMMU_BASE + 21)
#define CLK_PCLK_ISP1_SYSMMU			(CLK_SYSMMU_BASE + 22)
#define CLK_ACLK_ISP0_SYSMMU			(CLK_SYSMMU_BASE + 23)
#define CLK_PCLK_ISP0_SYSMMU			(CLK_SYSMMU_BASE + 24)
#define CLK_ACLK_TPU_SYSMMU			(CLK_SYSMMU_BASE + 25)
#define CLK_PCLK_TPU_SYSMMU			(CLK_SYSMMU_BASE + 26)

#define CLK_ACLK_VPP0_SYSMMU			(CLK_SYSMMU_BASE + 27)
#define CLK_ACLK_VPP1_SYSMMU			(CLK_SYSMMU_BASE + 28)
#define CLK_PCLK_VPP0_SYSMMU			(CLK_SYSMMU_BASE + 29)
#define CLK_PCLK_VPP1_SYSMMU			(CLK_SYSMMU_BASE + 30)

#define CLK_MSCL_BASE	600

#define CLK_MUX_ACLK_MSCL_532_USER		(CLK_MSCL_BASE + 10)
#define CLK_MUX_ACLK_MSCL_532_USER_ENABLE	(CLK_MSCL_BASE + 11)
#define CLK_MUX_ACLK_MSCL_532_USER_STAT		(CLK_MSCL_BASE + 12)

#define CLK_DIV_PCLK_MSCL_RATIO			(CLK_MSCL_BASE + 20)
#define CLK_DIV_PCLK_MSCL_STAT			(CLK_MSCL_BASE + 21)

#define CLK_ACLK_M2MSCALER0			(CLK_MSCL_BASE + 30)
#define CLK_ACLK_M2MSCALER1			(CLK_MSCL_BASE + 31)
#define CLK_ACLK_JPEG				(CLK_MSCL_BASE + 32)
#define CLK_ACLK_LH_ASYNC_SI_MSCL0		(CLK_MSCL_BASE + 33)
#define CLK_ACLK_LH_ASYNC_SI_MSCL1		(CLK_MSCL_BASE + 34)
#define CLK_ACLK_XIU_MSCLX			(CLK_MSCL_BASE + 35)
#define CLK_ACLK_XIU_MSCL1			(CLK_MSCL_BASE + 36)
#define CLK_ACLK_CP_MSCL0			(CLK_MSCL_BASE + 37)
#define CLK_ACLK_CP_MSCL1			(CLK_MSCL_BASE + 38)
#define CLK_ACLK_ACLK2ACEL_BRDG			(CLK_MSCL_BASE + 39)

#define CLK_PCLK_M2MSCALER0			(CLK_MSCL_BASE + 50)
#define CLK_PCLK_M2MSCALER1			(CLK_MSCL_BASE + 51)
#define CLK_PCLK_JPEG				(CLK_MSCL_BASE + 52)
#define CLK_PCLK_CP_MSCL0			(CLK_MSCL_BASE + 53)
#define CLK_PCLK_CP_MSCL1			(CLK_MSCL_BASE + 54)
#define CLK_ACLK_LH_MSCL0			(CLK_MSCL_BASE + 55)

#define CLK_SCLK_JPEG_GATED			(CLK_MSCL_BASE + 60)

#define CLK_G2D_BASE	700

#define CLK_ACLK_G2D_PPMU			(CLK_G2D_BASE + 10)
#define CLK_ACLK_G2D_ALB			(CLK_G2D_BASE + 11)
#define CLK_ACLK_G2D_XIU			(CLK_G2D_BASE + 12)
#define CLK_ACLK_G2D_ND_400			(CLK_G2D_BASE + 13)
#define CLK_ACLK_G2D_LH				(CLK_G2D_BASE + 14)
#define CLK_ACLK_G2D				(CLK_G2D_BASE + 15)
#define CLK_ACLK_G2D_BTS			(CLK_G2D_BASE + 16)

#define CLK_PCLK_G2D_PPMU			(CLK_G2D_BASE + 18)
#define CLK_PCLK_G2D_ALB			(CLK_G2D_BASE + 19)
#define CLK_PCLK_G2D				(CLK_G2D_BASE + 20)
#define CLK_PCLK_G2D_BTS			(CLK_G2D_BASE + 21)

#endif /* _DT_BINDINGS_CLOCK_EXYNOS_5250_H */
