obj-$(CONFIG_FIMC_IS_V4_0_0) += fimc-is-hw-pwr.o
obj-$(CONFIG_FIMC_IS_V4_0_0) += fimc-is-hw-chain.o

EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2/include
