obj-$(CONFIG_MEIZU_CAMERA_SPECIAL) += AfInit.o
obj-$(CONFIG_MEIZU_CAMERA_SPECIAL) += AfInter.o
obj-$(CONFIG_MEIZU_CAMERA_SPECIAL) += AfSTMV.o
obj-$(CONFIG_MEIZU_CAMERA_SPECIAL) += lc898212xd.o

EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2/include
