
# host notify driver
obj-$(CONFIG_USB_HOST_NOTIFY)		+= host_notify_class.o
obj-$(CONFIG_USB_NOTIFY_LAYER)		+= usb_notify_layer.o
usb_notify_layer-y			:= usb_notify.o dock_notify.o
obj-$(CONFIG_USB_NOTIFIER)		+= usb_notifier.o

