obj-$(CONFIG_EXYNOS_DECON_LCD_S6E3FA0)	+= s6e3fa0_mipi_lcd.o s6e3fa0_lcd_ctrl.o
obj-$(CONFIG_EXYNOS_DECON_LCD_S6E8AA0)	+= s6e8aa0_mipi_lcd.o 
obj-$(CONFIG_EXYNOS_DECON_LCD_S6E8FA0)	+= s6e8fa0x01_mipi_lcd.o 
obj-$(CONFIG_MEIZU_DECON_LCD_S6E3FA3)	+= s6e3fa3_mipi_lcd.o
