obj-$(CONFIG_SOC_EXYNOS5422) += gud-exynos5422/
obj-$(CONFIG_SOC_EXYNOS5430) += gud-exynos5430/
obj-$(CONFIG_SOC_EXYNOS5433) += gud-exynos5433/
obj-$(CONFIG_SOC_EXYNOS7420) += gud-exynos7420/
obj-$(CONFIG_TRUSTONIC_TRUSTED_UI) += TlcTui/
