obj-$(CONFIG_EXYNOS_DECON_DISPLAY)	+= decon_display_driver.o
obj-y                                   += decon_debug.o
obj-$(CONFIG_DECON_MIC)			+= decon_mic.o mic_reg_5430.o
obj-$(CONFIG_DECON_MIPI_DSI)		+= decon_mipi_dsi.o dsim_reg_5430.o
obj-$(CONFIG_SOC_EXYNOS5430)		+= decon_dt_exynos5430.o decon_pm_exynos5430.o decon_fb.o decon_reg_5430.o
obj-$(CONFIG_SOC_EXYNOS5433)		+= decon_dt_exynos5430.o decon_pm_exynos5430.o decon_fb.o decon_reg_5430.o
obj-$(CONFIG_FB_HIBERNATION_DISPLAY)	+= decon_pm_core.o
